@if ($errors->any())<div class="alert alert-danger">入力内容を確認してください。</div>@endif
<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="employee_number">社員番号 <span class="text-danger">*</span></label><input class="form-control @error('employee_number') is-invalid @enderror" id="employee_number" name="employee_number" value="{{ old('employee_number', $employee->employee_number ?? '') }}" required>@error('employee_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="name">氏名 <span class="text-danger">*</span></label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $employee->name ?? '') }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="department">部署</label><input class="form-control @error('department') is-invalid @enderror" id="department" name="department" value="{{ old('department', $employee->department ?? '') }}">@error('department')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="joined_at">入社日</label><input class="form-control @error('joined_at') is-invalid @enderror" id="joined_at" name="joined_at" type="date" value="{{ old('joined_at', isset($employee) ? $employee->joined_at?->format('Y-m-d') : '') }}">@error('joined_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="email">メールアドレス</label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" value="{{ old('email', $employee->email ?? '') }}">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
<div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-outline-secondary" href="{{ route('employees.index') }}">キャンセル</a><button class="btn btn-primary">保存する</button></div>
